version: "3"

services:
  db:
    image: mysql
    ports: [ "3306:3306" ]
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: [ "8000:80" ]
    environment:
      - PMA_ARBITRARY=1

